// src/components/Changelog.tsx
import { IconCircleDot, IconTag } from '@tabler/icons-solidjs'
import markdownit from 'markdown-it'
import { type Component, For, Show, createMemo } from 'solid-js'
import type { ReleaseInfo } from '~/apis'

// Format date to relative or short format
const formatDate = (dateString: string) => {
  const date = new Date(dateString)
  const now = new Date()
  const diffMs = now.getTime() - date.getTime()
  const diffDays = Math.floor(diffMs / (1000 * 60 * 60 * 24))

  if (diffDays === 0) return 'Today'

  if (diffDays === 1) return 'Yesterday'

  if (diffDays < 7) return `${diffDays} days ago`

  if (diffDays < 30) return `${Math.floor(diffDays / 7)} weeks ago`

  if (diffDays < 365) return `${Math.floor(diffDays / 30)} months ago`

  return date.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
  })
}

// Markdown renderer with target="_blank" for links
const createMarkdownRenderer = () => {
  const md = markdownit()

  const defaultRender =
    md.renderer.rules.link_open ||
    function (tokens, idx, options, _env, self) {
      return self.renderToken(tokens, idx, options)
    }

  md.renderer.rules.link_open = function (tokens, idx, options, env, self) {
    tokens[idx].attrSet('target', '_blank')

    return defaultRender(tokens, idx, options, env, self)
  }

  return md
}

const md = createMarkdownRenderer()

// Single changelog item for timeline
const TimelineItem: Component<{
  release: ReleaseInfo
  isFirst: boolean
  isLast: boolean
}> = (props) => {
  const body = createMemo(() => md.render(props.release.changelog || ''))

  return (
    <li>
      <Show when={!props.isFirst}>
        <hr class={props.release.isCurrent ? 'bg-primary' : ''} />
      </Show>

      <div class="timeline-start text-xs opacity-60">
        {formatDate(props.release.publishedAt)}
      </div>

      <div class="timeline-middle">
        <Show
          when={props.release.isCurrent}
          fallback={
            <IconTag class="h-5 w-5 text-base-content/50" stroke-width={1.5} />
          }
        >
          <IconCircleDot class="h-5 w-5 text-primary" stroke-width={2} />
        </Show>
      </div>

      <div
        class="timeline-end mb-4 timeline-box"
        classList={{
          'border-primary bg-primary/10': props.release.isCurrent,
        }}
      >
        <div class="mb-2 flex items-center gap-2">
          <span
            class="font-mono text-sm font-semibold"
            classList={{
              'text-primary': props.release.isCurrent,
            }}
          >
            {props.release.version}
          </span>
          <Show when={props.release.isCurrent}>
            <span class="badge badge-xs badge-primary">Current</span>
          </Show>
        </div>

        <Show when={props.release.changelog}>
          <div
            class="prose prose-sm max-w-none font-sans text-base-content/80"
            innerHTML={body()}
          />
        </Show>
      </div>

      <Show when={!props.isLast}>
        <hr class={props.release.isCurrent ? 'bg-primary' : ''} />
      </Show>
    </li>
  )
}

// Timeline changelog component
export const Changelog: Component<{
  releases: ReleaseInfo[]
  isLoading?: boolean
}> = (props) => {
  return (
    <div class="w-full max-w-md">
      <Show
        when={!props.isLoading}
        fallback={
          <div class="flex items-center justify-center py-8">
            <span class="loading loading-md loading-spinner" />
          </div>
        }
      >
        <Show
          when={props.releases.length > 0}
          fallback={
            <div class="py-4 text-center text-sm opacity-60">
              No releases found
            </div>
          }
        >
          <ul class="timeline timeline-vertical timeline-compact">
            <For each={props.releases}>
              {(release, index) => (
                <TimelineItem
                  release={release}
                  isFirst={index() === 0}
                  isLast={index() === props.releases.length - 1}
                />
              )}
            </For>
          </ul>
        </Show>
      </Show>
    </div>
  )
}

// packages/ui/components/Changelog.vue
<script setup lang="ts">
import type { ReleaseInfo } from '~/types'
import markdownit from 'markdown-it'

interface Props {
  releases: ReleaseInfo[]
  isLoading?: boolean
}

defineProps<Props>()

// Format date to relative or short format
function formatDate(dateString: string) {
  const date = new Date(dateString)
  const now = new Date()
  const diffMs = now.getTime() - date.getTime()
  const diffDays = Math.floor(diffMs / (1000 * 60 * 60 * 24))

  if (diffDays === 0) return 'Today'
  if (diffDays === 1) return 'Yesterday'
  if (diffDays < 7) return `${diffDays} days ago`
  if (diffDays < 30) return `${Math.floor(diffDays / 7)} weeks ago`
  if (diffDays < 365) return `${Math.floor(diffDays / 30)} months ago`

  return date.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
  })
}

// Markdown renderer with target="_blank" for links
function createMarkdownRenderer() {
  const md = markdownit()

  const defaultRender =
    md.renderer.rules.link_open ||
    function (tokens, idx, options, _env, self) {
      return self.renderToken(tokens, idx, options)
    }

  md.renderer.rules.link_open = function (tokens, idx, options, env, self) {
    tokens[idx]?.attrSet('target', '_blank')
    return defaultRender(tokens, idx, options, env, self)
  }

  return md
}

const md = createMarkdownRenderer()

const renderMarkdown = (content: string) => md.render(content)
</script>

<template>
  <div class="w-full max-w-[28rem] min-w-[20rem]">
    <template v-if="!isLoading">
      <template v-if="releases.length > 0">
        <ul class="m-0 list-none p-0">
          <li
            v-for="release in releases"
            :key="release.version"
            class="flex gap-3"
          >
            <div
              class="changelog-line flex shrink-0 flex-col items-center pt-1"
            >
              <div
                class="changelog-dot h-2.5 w-2.5 shrink-0 rounded-full"
                :class="release.isCurrent ? 'changelog-dot-current' : ''"
              />
            </div>

            <div class="min-w-0 flex-1 pb-4">
              <div class="mb-2 flex flex-col gap-1">
                <time class="text-[0.6875rem] text-base-content/50">
                  {{ formatDate(release.publishedAt) }}
                </time>
                <div class="flex items-center gap-1.5">
                  <span
                    class="font-mono text-sm font-semibold text-base-content"
                    :class="{ 'text-primary': release.isCurrent }"
                  >
                    {{ release.version }}
                  </span>
                  <span
                    v-if="release.isCurrent"
                    class="inline-flex items-center rounded-full bg-primary px-1.5 py-0.5 text-[0.625rem] font-semibold tracking-wide text-primary-content uppercase"
                  >
                    Current
                  </span>
                </div>
              </div>

              <div
                v-if="release.changelog"
                class="changelog-body text-[0.8125rem] leading-normal text-base-content/80"
                v-html="renderMarkdown(release.changelog)"
              />
            </div>
          </li>
        </ul>
      </template>
      <div v-else class="p-4 text-center text-sm text-base-content/50">
        No releases found
      </div>
    </template>
    <div v-else class="flex items-center justify-center p-8">
      <span class="changelog-spinner h-6 w-6 rounded-full" />
    </div>
  </div>
</template>

<style scoped>
.changelog-dot {
  background: color-mix(in oklab, var(--color-base-content) 30%, transparent);
}

.changelog-dot-current {
  background: var(--color-primary);
  box-shadow: 0 0 8px color-mix(in oklab, var(--color-primary) 50%, transparent);
}

.changelog-item:not(:last-child) .changelog-line::after {
  content: '';
  flex: 1;
  width: 2px;
  margin-top: 0.375rem;
  background: color-mix(in oklab, var(--color-base-content) 15%, transparent);
}

.changelog-body :deep(a) {
  color: var(--color-primary);
  text-decoration: underline;
}

.changelog-body :deep(a:hover) {
  opacity: 0.8;
}

.changelog-body :deep(p) {
  margin: 0.25rem 0;
}

.changelog-body :deep(ul) {
  margin: 0.25rem 0;
  padding-left: 1rem;
}

.changelog-body :deep(li) {
  margin: 0.125rem 0;
}

.changelog-body :deep(code) {
  font-size: 0.75rem;
  padding: 0.125rem 0.25rem;
  border-radius: 0.25rem;
  background: color-mix(in oklab, var(--color-base-content) 10%, transparent);
}

.changelog-spinner {
  border: 2px solid
    color-mix(in oklab, var(--color-base-content) 20%, transparent);
  border-top-color: var(--color-primary);
  animation: spin 0.6s linear infinite;
}

@keyframes spin {
  to {
    transform: rotate(360deg);
  }
}
</style>
