// pages/overview.vue
<script setup lang="ts">
import type Highcharts from 'highcharts'
import type { ChartRef } from '~/components/RealtimeLineChart.vue'
import byteSize from 'byte-size'
import { getChartThemeColors } from '~/utils'

useHead({ title: 'Overview' })

const { t } = useI18n()
const globalStore = useGlobalStore()
const connectionsStore = useConnectionsStore()
const endpointStore = useEndpointStore()

const formatBytes = (bytes: number) => byteSize(bytes).toString()

// Chart refs
const trafficChartRef = ref<{ chartRef: ChartRef }>()
const memoryChartRef = ref<{ chartRef: ChartRef }>()

// Traffic chart config
const trafficSeriesConfig = computed(() => [
  { name: t('down'), color: '#7cb5ec' },
  { name: t('up'), color: '#90ed7d' },
])

const trafficInitialData = computed(() => [
  [...globalStore.trafficChartHistory.download],
  [...globalStore.trafficChartHistory.upload],
])

// Memory chart config
const memorySeriesConfig = computed(() => [
  { name: t('memory'), color: '#f7a35c' },
])

const memoryInitialData = computed(() => [[...globalStore.memoryChartHistory]])

// Flow chart (pie chart) options
const flowChartOptions = computed<Highcharts.Options>(() => {
  const themeColors = getChartThemeColors()

  return {
    chart: {
      type: 'pie',
      backgroundColor: themeColors.backgroundColor,
      animation: false,
    },
    credits: {
      enabled: false,
    },
    title: {
      text: t('flow'),
      style: {
        color: themeColors.textColor,
      },
    },
    tooltip: {
      pointFormatter() {
        const value = this.y || 0
        const percent =
          (this as Highcharts.Point & { percentage?: number }).percentage || 0

        return `${this.name}<br/>${byteSize(value).toString()} (${percent.toFixed(1)}%)`
      },
    },
    plotOptions: {
      pie: {
        allowPointSelect: true,
        cursor: 'pointer',
        dataLabels: {
          enabled: false,
        },
        showInLegend: true,
        animation: false,
      },
    },
    legend: {
      itemStyle: {
        color: themeColors.textColor,
      },
      itemHoverStyle: {
        color: themeColors.textColorHover,
      },
    },
    series: [
      {
        type: 'pie',
        name: t('flow'),
        data: [
          {
            name: t('downloadTotal'),
            y: connectionsStore.latestConnectionMsg?.downloadTotal || 0,
            color: themeColors.seriesColors[0],
          },
          {
            name: t('uploadTotal'),
            y: connectionsStore.latestConnectionMsg?.uploadTotal || 0,
            color: themeColors.seriesColors[1],
          },
        ],
      },
    ],
  }
})

// Track previous times to prevent duplicate points on remount
let prevTrafficTime =
  globalStore.trafficChartHistory.download.length > 0
    ? globalStore.trafficChartHistory.download[
        globalStore.trafficChartHistory.download.length - 1
      ][0]
    : 0

let prevMemoryTime =
  globalStore.memoryChartHistory.length > 0
    ? globalStore.memoryChartHistory[
        globalStore.memoryChartHistory.length - 1
      ][0]
    : 0

// Watch for traffic updates and add to chart
watch(
  () => globalStore.latestTraffic,
  (newTraffic) => {
    if (newTraffic && trafficChartRef.value?.chartRef) {
      const time = Date.now()

      // Only add points if time has advanced (prevents duplicate points on remount)
      if (time > prevTrafficTime) {
        trafficChartRef.value.chartRef.addPoints([
          { seriesIndex: 0, time, value: newTraffic.down },
          { seriesIndex: 1, time, value: newTraffic.up },
        ])
        // Store in global history
        globalStore.addTrafficDataPoint(time, newTraffic.down, newTraffic.up)
        prevTrafficTime = time
      }
    }
  },
)

// Watch for memory updates and add to chart
watch(
  () => globalStore.latestMemory?.inuse,
  (newMemory) => {
    if (newMemory && memoryChartRef.value?.chartRef) {
      const time = Date.now()

      // Only add points if time has advanced (prevents duplicate points on remount)
      if (time > prevMemoryTime) {
        memoryChartRef.value.chartRef.addPoint(0, time, newMemory)
        // Store in global history
        globalStore.addMemoryDataPoint(time, newMemory)
        prevMemoryTime = time
      }
    }
  },
)
</script>

<template>
  <div class="flex flex-col gap-2 lg:h-full">
    <!-- Stats -->
    <div
      class="stats grid w-full shrink-0 stats-vertical grid-cols-2 bg-primary shadow lg:flex lg:stats-horizontal"
    >
      <TrafficWidget :label="t('upload')">
        {{ formatBytes(globalStore.latestTraffic?.up || 0) }}/s
      </TrafficWidget>

      <TrafficWidget :label="t('download')">
        {{ formatBytes(globalStore.latestTraffic?.down || 0) }}/s
      </TrafficWidget>

      <TrafficWidget :label="t('uploadTotal')">
        {{
          formatBytes(connectionsStore.latestConnectionMsg?.uploadTotal || 0)
        }}
      </TrafficWidget>

      <TrafficWidget :label="t('downloadTotal')">
        {{
          formatBytes(connectionsStore.latestConnectionMsg?.downloadTotal || 0)
        }}
      </TrafficWidget>

      <TrafficWidget :label="t('activeConnections')">
        {{ connectionsStore.latestConnectionMsg?.connections?.length || 0 }}
      </TrafficWidget>

      <TrafficWidget :label="t('memoryUsage')">
        {{ formatBytes(globalStore.latestMemory?.inuse || 0) }}
      </TrafficWidget>
    </div>

    <!-- Charts -->
    <div
      class="grid grid-cols-1 gap-2 rounded-box bg-base-300 py-4 lg:grid-cols-3"
    >
      <div class="h-80">
        <RealtimeLineChart
          ref="trafficChartRef"
          :title="t('traffic')"
          :series-config="trafficSeriesConfig"
          :initial-data="trafficInitialData"
          :is-loading="!globalStore.latestTraffic"
        />
      </div>

      <div class="h-80">
        <HighchartsAutoSize
          :options="flowChartOptions"
          :is-loading="
            !connectionsStore.latestConnectionMsg?.connections?.length
          "
        />
      </div>

      <div class="h-80">
        <RealtimeLineChart
          ref="memoryChartRef"
          :title="t('memory')"
          :series-config="memorySeriesConfig"
          :initial-data="memoryInitialData"
          :is-loading="!globalStore.latestMemory"
        />
      </div>
    </div>

    <!-- Data Usage Table -->
    <DataUsageTable />

    <!-- Footer -->
    <footer
      class="mx-auto mt-4 footer block footer-horizontal rounded-box bg-neutral p-4 text-center text-lg font-bold text-neutral-content"
    >
      {{ endpointStore.currentEndpoint?.url }}
    </footer>
  </div>
</template>

// src/pages/Overview.tsx
import { makeTimer } from '@solid-primitives/timer'
import type { ApexOptions } from 'apexcharts'
import byteSize from 'byte-size'
import { merge } from 'lodash'
import { SolidApexCharts } from 'solid-apexcharts'
import {
  JSX,
  ParentComponent,
  batch,
  children,
  createEffect,
  createMemo,
  createSignal,
} from 'solid-js'
import { CHART_MAX_XAXIS, DEFAULT_CHART_OPTIONS } from '~/constants'
import { useI18n } from '~/i18n'
import { endpoint, latestConnectionMsg, useWsRequest } from '~/signals'

const TrafficWidget: ParentComponent<{ label: JSX.Element }> = (props) => (
  <div class="stat flex-1 place-items-center">
    <div class="stat-title text-primary-content">{props.label}</div>
    <div class="stat-value text-2xl text-primary-content lg:text-3xl">
      {children(() => props.children)()}
    </div>
  </div>
)

export default () => {
  const [t] = useI18n()

  const [traffics, setTraffics] = createSignal<{ down: number; up: number }[]>(
    [],
  )
  const [memories, setMemories] = createSignal<number[]>([])

  // https://github.com/apexcharts/apexcharts.js/blob/main/samples/source/line/realtime.xml
  // TODO: needs a better way
  makeTimer(
    () => {
      batch(() => {
        setTraffics((traffics) => traffics.slice(-CHART_MAX_XAXIS))
        setMemories((memo) => memo.slice(-CHART_MAX_XAXIS))
      })
    },
    // we shrink the chart data array size down every minute to prevent memory leaks
    60 * 1000,
    setInterval,
  )

  const traffic = useWsRequest<{ down: number; up: number }>('traffic')

  createEffect(() => {
    const t = traffic()

    if (t) setTraffics((traffics) => [...traffics, t])
  })

  const trafficChartOptions = createMemo<ApexOptions>(() =>
    merge({ title: { text: t('traffic') } }, DEFAULT_CHART_OPTIONS),
  )

  const trafficChartSeries = createMemo(() => [
    {
      name: t('down'),
      data: traffics().map((t) => t.down),
    },
    {
      name: t('up'),
      data: traffics().map((t) => t.up),
    },
  ])

  const memory = useWsRequest<{ inuse: number }>('memory')

  createEffect(() => {
    const m = memory()?.inuse

    if (m) setMemories((memories) => [...memories, m])
  })

  const memoryChartOptions = createMemo<ApexOptions>(() =>
    merge({ title: { text: t('memory') } }, DEFAULT_CHART_OPTIONS),
  )

  const memoryChartSeries = createMemo(() => [
    { name: t('memory'), data: memories() },
  ])

  return (
    <div class="flex flex-col gap-2">
      <div class="stats stats-vertical w-full grid-cols-2 bg-primary shadow lg:stats-horizontal lg:flex">
        <TrafficWidget label={t('upload')}>
          {byteSize(traffic()?.up || 0).toString()}/s
        </TrafficWidget>

        <TrafficWidget label={t('download')}>
          {byteSize(traffic()?.down || 0).toString()}/s
        </TrafficWidget>

        <TrafficWidget label={t('uploadTotal')}>
          {byteSize(latestConnectionMsg()?.uploadTotal || 0).toString()}
        </TrafficWidget>

        <TrafficWidget label={t('downloadTotal')}>
          {byteSize(latestConnectionMsg()?.downloadTotal || 0).toString()}
        </TrafficWidget>

        <TrafficWidget label={t('activeConnections')}>
          {latestConnectionMsg()?.connections?.length || 0}
        </TrafficWidget>

        <TrafficWidget label={t('memoryUsage')}>
          {byteSize(memory()?.inuse || 0).toString()}
        </TrafficWidget>
      </div>

      <div class="rounded-box flex flex-col gap-2 bg-base-300 py-4 lg:flex-row">
        <div class="flex-1">
          <SolidApexCharts
            type="area"
            options={trafficChartOptions()}
            series={trafficChartSeries()}
          />
        </div>
        <div class="flex-1">
          <SolidApexCharts
            type="line"
            options={memoryChartOptions()}
            series={memoryChartSeries()}
          />
        </div>
      </div>

      <footer class="footer rounded-box mx-auto mt-4 block bg-neutral p-4 text-center text-lg font-bold text-neutral-content">
        {endpoint()?.url}
      </footer>
    </div>
  )
}
