// pages/rules.vue
<script setup lang="ts">
import type { Rule, RuleProvider } from '~/types'
import { IconReload } from '@tabler/icons-vue'
import { matchSorter } from 'match-sorter'
import {
  useRuleProvidersQuery,
  useRulesQuery,
  useUpdateRuleProviderMutation,
} from '~/composables/useQueries'
import { formatTimeFromNow, useStringBooleanMap } from '~/utils'

useHead({ title: 'Rules' })

const { t } = useI18n()
const configStore = useConfigStore()

// TanStack Query
const { data: rules = ref([]), isLoading: isLoadingRules } = useRulesQuery()
const { data: ruleProviders = ref([]), isLoading: isLoadingProviders } =
  useRuleProvidersQuery()
const updateProviderMutation = useUpdateRuleProviderMutation()

const activeTab = ref<'rules' | 'ruleProviders'>('rules')
const globalFilter = ref('')

const { map: updatingMap, setWithCallback: setUpdatingMap } =
  useStringBooleanMap()

const tabs = computed(() => [
  {
    type: 'rules' as const,
    name: t('rules'),
    count: rules.value?.length ?? 0,
  },
  {
    type: 'ruleProviders' as const,
    name: t('ruleProviders'),
    count: ruleProviders.value?.length ?? 0,
  },
])

const filteredRules = computed(() =>
  globalFilter.value
    ? matchSorter(rules.value ?? [], globalFilter.value, {
        keys: ['type', 'payload', 'proxy'] as (keyof Rule)[],
      })
    : (rules.value ?? []),
)

const filteredRuleProviders = computed(() =>
  globalFilter.value
    ? matchSorter(ruleProviders.value ?? [], globalFilter.value, {
        keys: ['name', 'vehicleType', 'behavior'] as (keyof RuleProvider)[],
      })
    : (ruleProviders.value ?? []),
)

async function onUpdateProvider(name: string) {
  await setUpdatingMap(name, () => updateProviderMutation.mutateAsync(name))
}

async function onUpdateAllProvider() {
  const providers = ruleProviders.value ?? []
  await Promise.all(
    providers.map((provider) =>
      updateProviderMutation.mutateAsync(provider.name),
    ),
  )
}

const isLoading = computed(
  () => isLoadingRules.value || isLoadingProviders.value,
)
const allProviderIsUpdating = computed(
  () => updateProviderMutation.isPending.value,
)
</script>

<template>
  <div class="flex h-full flex-col gap-2">
    <!-- Loading State -->
    <div v-if="isLoading" class="flex flex-1 items-center justify-center">
      <span class="loading loading-lg loading-spinner" />
    </div>

    <template v-else>
      <!-- Tabs and Search -->
      <div class="flex w-full flex-wrap items-center gap-2">
        <div class="tabs-box tabs gap-2 tabs-sm">
          <button
            v-for="tab in tabs"
            :key="tab.type"
            class="tab gap-2 px-2"
            :class="{ 'bg-primary text-neutral!': activeTab === tab.type }"
            @click="activeTab = tab.type"
          >
            <span>{{ tab.name }}</span>
            <div class="badge badge-sm">
              {{ tab.count }}
            </div>
          </button>
        </div>

        <div class="join flex flex-1 items-center">
          <input
            v-model="globalFilter"
            class="input input-sm join-item flex-1 input-primary"
            type="search"
            :placeholder="t('search')"
          />

          <Button
            v-if="activeTab === 'ruleProviders'"
            class="btn join-item btn-sm btn-primary"
            :disabled="allProviderIsUpdating"
            @click="onUpdateAllProvider"
          >
            <IconReload
              :class="{ 'animate-spin text-success': allProviderIsUpdating }"
            />
          </Button>
        </div>
      </div>

      <!-- Rules List -->
      <div
        v-if="activeTab === 'rules'"
        class="flex-1 space-y-2 overflow-y-auto"
      >
        <div
          v-for="rule in filteredRules"
          :key="`${rule.type}-${rule.payload}-${rule.proxy}`"
          class="card bg-base-200 p-4 card-sm card-border"
        >
          <div class="flex items-center gap-2">
            <span class="break-all">{{ rule.payload }}</span>
            <div v-if="rule.size !== -1" class="badge badge-sm">
              {{ rule.size }}
            </div>
          </div>
          <div class="text-xs text-slate-500">
            {{ rule.type }} :: {{ rule.proxy }}
          </div>
        </div>

        <div
          v-if="filteredRules.length === 0"
          class="py-8 text-center text-base-content/70"
        >
          No rules
        </div>
      </div>

      <!-- Rule Providers List -->
      <div v-else class="flex-1 space-y-2 overflow-y-auto">
        <div
          v-for="provider in filteredRuleProviders"
          :key="`${provider.type}-${provider.name}`"
          class="card relative bg-base-200 p-4 card-sm card-border"
        >
          <div class="flex items-center gap-2 pr-8">
            <span class="break-all">{{ provider.name }}</span>
            <div class="badge badge-sm">
              {{ provider.ruleCount }}
            </div>
          </div>

          <div class="text-xs text-slate-500">
            {{ provider.vehicleType }} / {{ provider.behavior }} /
            {{ t('updated') }}
            {{ formatTimeFromNow(provider.updatedAt, configStore.locale) }}
          </div>

          <Button
            class="absolute top-2 right-2 mr-2 btn-circle h-4 btn-sm"
            :disabled="updatingMap[provider.name]"
            @click="onUpdateProvider(provider.name)"
          >
            <IconReload
              :class="{
                'animate-spin text-success': updatingMap[provider.name],
              }"
            />
          </Button>
        </div>

        <div
          v-if="filteredRuleProviders.length === 0"
          class="py-8 text-center text-base-content/70"
        >
          No rule providers
        </div>
      </div>
    </template>
  </div>
</template>

// src/pages/Rules.tsx
import { useI18n } from '@solid-primitives/i18n'
import { IconReload } from '@tabler/icons-solidjs'
import InfiniteScroll from 'solid-infinite-scroll'
import { For, Show, createMemo, createSignal, onMount } from 'solid-js'
import { twMerge } from 'tailwind-merge'
import { Button } from '~/components'
import { formatTimeFromNow, useStringBooleanMap } from '~/helpers'
import { renderRulesAndProviderInTwoColumns, useRules } from '~/signals'

export default () => {
  const [t] = useI18n()
  const {
    rules,
    rulesProviders,
    updateRules,
    updateAllRuleProvider,
    updateRuleProviderByName,
  } = useRules()
  const [maxRuleRender, setMaxRuleRender] = createSignal(100)
  const renderRules = createMemo(() => rules().slice(0, maxRuleRender()))

  onMount(updateRules)

  const { map: updatingMap, setWithCallback: setUpdatingMap } =
    useStringBooleanMap()
  const [allProviderIsUpdating, setAllProviderIsUpdating] = createSignal(false)

  const onUpdateProviderClick = (e: MouseEvent, name: string) => {
    e.stopPropagation()
    void setUpdatingMap(name, () => updateRuleProviderByName(name))
  }

  const onUpdateAllProviderClick = async (e: MouseEvent) => {
    e.stopPropagation()
    setAllProviderIsUpdating(true)
    try {
      await updateAllRuleProvider()
    } catch {}
    setAllProviderIsUpdating(false)
  }

  return (
    <div
      class={twMerge(
        'flex w-full flex-col gap-4',
        renderRulesAndProviderInTwoColumns() && 'flex-row',
      )}
    >
      <div class="flex-1">
        <h1 class="pb-4 text-lg font-semibold">{t('rules')}</h1>

        <InfiniteScroll
          each={renderRules()}
          hasMore={renderRules().length < rules().length}
          next={() => setMaxRuleRender(maxRuleRender() + 100)}
        >
          {(rule) => (
            <div class="card card-bordered card-compact mb-2 bg-base-200 p-4">
              <div class="flex items-center gap-2">
                <span class="break-all">{rule.payload}</span>
                <Show when={typeof rule.size === 'number' && rule.size !== -1}>
                  <div class="badge badge-sm">{rule.size}</div>
                </Show>
              </div>
              <div class="text-xs text-slate-500">
                {rule.type} :: {rule.proxy}
              </div>
            </div>
          )}
        </InfiniteScroll>
      </div>

      <Show when={rulesProviders().length > 0}>
        <div class="flex-1">
          <h1 class="flex h-11 items-center gap-2 pb-4 text-lg font-semibold">
            {t('ruleProviders')}
            <Button
              class="btn-circle btn-sm"
              disabled={allProviderIsUpdating()}
              onClick={(e) => onUpdateAllProviderClick(e)}
            >
              <IconReload
                class={twMerge(
                  allProviderIsUpdating() && 'animate-spin text-success',
                )}
              />
            </Button>
          </h1>

          <For each={rulesProviders()}>
            {(rulesProvider) => (
              <div class="card card-bordered card-compact mb-2 bg-base-200 p-4">
                <div class="flex items-center gap-2 pr-8">
                  <span class="break-all">{rulesProvider.name}</span>
                  <div class="badge badge-sm">{rulesProvider.ruleCount}</div>
                </div>

                <div class="text-xs text-slate-500">
                  {rulesProvider.vehicleType} / {rulesProvider.behavior} /
                  {t('updated')} {formatTimeFromNow(rulesProvider.updatedAt)}
                </div>

                <Button
                  class="btn-circle btn-sm absolute right-2 top-2 mr-2 h-4"
                  disabled={updatingMap()[rulesProvider.name]}
                  onClick={(e) => onUpdateProviderClick(e, rulesProvider.name)}
                >
                  <IconReload
                    class={twMerge(
                      updatingMap()[rulesProvider.name] &&
                        'animate-spin text-success',
                    )}
                  />
                </Button>
              </div>
            )}
          </For>
        </div>
      </Show>
    </div>
  )
}
