// components/ProxyPreviewBar.vue
<script setup lang="ts">
interface Props {
  proxyNameList: string[]
  testUrl: string | null
  now?: string
}

const props = defineProps<Props>()

const proxiesStore = useProxiesStore()
const configStore = useConfigStore()

const latencyList = computed(() =>
  props.proxyNameList.map((name) =>
    proxiesStore.getLatencyByName(name, props.testUrl),
  ),
)

const all = computed(() => latencyList.value.length || 1)

const good = computed(
  () =>
    latencyList.value.filter(
      (latency) =>
        latency > configStore.latencyQualityMap.NOT_CONNECTED &&
        latency <= configStore.latencyQualityMap.MEDIUM,
    ).length,
)

const middle = computed(
  () =>
    latencyList.value.filter(
      (latency) =>
        latency > configStore.latencyQualityMap.MEDIUM &&
        latency <= configStore.latencyQualityMap.HIGH,
    ).length,
)

const slow = computed(
  () =>
    latencyList.value.filter(
      (latency) => latency > configStore.latencyQualityMap.HIGH,
    ).length,
)

const notConnected = computed(
  () =>
    latencyList.value.filter(
      (latency) => latency === configStore.latencyQualityMap.NOT_CONNECTED,
    ).length,
)

const goodPercent = computed(() => (good.value * 100) / all.value)
const middlePercent = computed(() => (middle.value * 100) / all.value)
const slowPercent = computed(() => (slow.value * 100) / all.value)
const notConnectedPercent = computed(
  () => (notConnected.value * 100) / all.value,
)
</script>

<template>
  <div class="flex items-center gap-2">
    <div
      class="my-1 flex flex-1 items-center justify-center overflow-hidden rounded-2xl [&>*]:h-2"
    >
      <div class="bg-green-600" :style="{ width: `${goodPercent}%` }" />
      <div class="bg-yellow-500" :style="{ width: `${middlePercent}%` }" />
      <div class="bg-red-500" :style="{ width: `${slowPercent}%` }" />
      <div class="bg-neutral" :style="{ width: `${notConnectedPercent}%` }" />
    </div>

    <Latency v-if="now" :proxy-name="now" :test-url="testUrl" />
  </div>
</template>

// src/components/ProxyPreviewBar.tsx
import { createMemo } from 'solid-js'
import { Latency } from '~/components'
import { latencyQualityMap, useProxies } from '~/signals'

export const ProxyPreviewBar = (props: {
  proxyNameList: string[]
  now?: string
}) => {
  const { latencyMap } = useProxies()
  const latencyList = createMemo(() =>
    props.proxyNameList.map((name) => latencyMap()[name]),
  )

  const all = createMemo(() => latencyList().length)
  const good = createMemo(
    () =>
      latencyList().filter(
        (latency) =>
          latency > latencyQualityMap().NOT_CONNECTED &&
          latency <= latencyQualityMap().MEDIUM,
      ).length,
  )
  const middle = createMemo(
    () =>
      latencyList().filter(
        (latency) =>
          latency > latencyQualityMap().MEDIUM &&
          latency <= latencyQualityMap().HIGH,
      ).length,
  )
  const slow = createMemo(
    () =>
      latencyList().filter((latency) => latency > latencyQualityMap().HIGH)
        .length,
  )
  const notConnected = createMemo(
    () =>
      latencyList().filter(
        (latency) => latency === latencyQualityMap().NOT_CONNECTED,
      ).length,
  )

  return (
    <div class="flex h-6 w-full items-center gap-2">
      <div class="flex flex-1 overflow-hidden rounded-2xl">
        <div
          class="h-2 bg-success"
          style={{
            width: `${(good() * 100) / all()}%`, // cant use tw class, otherwise dynamic classname won't be generated
          }}
        />
        <div
          class="h-2 bg-warning"
          style={{
            width: `${(middle() * 100) / all()}%`,
          }}
        />
        <div
          class="h-2 bg-error"
          style={{
            width: `${(slow() * 100) / all()}%`,
          }}
        />
        <div
          class="h-2 bg-neutral"
          style={{
            width: `${(notConnected() * 100) / all()}%`,
          }}
        />
      </div>

      <Latency name={props.now} />
    </div>
  )
}
